### ISSUE TITLE
Why is `ValueNthElementKey` works only for array/map/function but not for sciter Object type

### ISSUE THREAD

**Issue by oskca** [c-smile/sciter-sdk#22]
See https://github.com/oskca/sciter/issues/17. In order to get the keys of an sciter object type, one have to use `EnumerateKeyValue`, because `ValueNthElementKey(idx)` always returns NULL value.
```json
{
    "string":"hello",
    "number":123
}
```
While `ValueElementsCount` both works on `array/map/function` and on sciter `Object` type, should `ValueNthElementKey` supports all those composit types?

**Comment by c-smile** [comment]
Script object is an **unordered** map of name/value pairs so it does not provide indexed access. 
Moreover internal implementation of object inside script is pure hash map with collision lists. 
Getting nth-element key/value from object is `O(N)` complex operation. And if you want to do something like this : 

```
for( int n = 0; n < length; ++n)  
  VALUE k = ValueNthElementKey(obj, idx);

```
You will get `O(N*N)` complex operation. I simply don't want even to enable this possibility in API.

Options:

- Use `ValueIsolate(obj)` - after the call all script objects will be converted to JSON dictionaries (that have indexed access by design).

- Use `EnumerateKeyValue`

**Comment by oskca** [comment]
Thank you for you explanation. That makes good sense for me :smile:
