### ISSUE TITLE
Where is libsciter-gtk-32.so ?

### ISSUE THREAD

**Issue by GeraldWodni** [c-smile/sciter-sdk#61]
We are evaluating the use of Sciter in an application which was a breeze on Windows. However for Linux we cannot find a 32bit so. The sources suggest that there should be one:

https://github.com/c-smile/sciter-sdk/blob/ee52daf1814c9a7952c9e06d48f2d8bbd48e6b50/include/sciter-x-types.h#L253

Do we have to purchase a license to get access to the 32bit version?

**Comment by pravic** [comment]
To be more precise, you should *build* 32-bit version. And to build, you need Sciter source code. So yes, you need to purchase it.

But why do you need 32-bit on Linux? Linux is 64-bit mostly.

**Comment by GeraldWodni** [comment]
@pravic  thanks for the fast response!

> But why do you need 32-bit on Linux? Linux is 64-bit mostly.

Agreed, but the application core is 32-bit and uses lots of dynamic code generation, so it would be of great use to us to start working with a 32-bit Linux version (especially as there are 32-bit versions for OS-X and Windows). The application is huge and is already being ported but it will take another 6-12 months. Even then we will still want to support all 3 operating systems in 32 and 64-bit.

It just seems a bit arbitrary that the Versions for Windows and OS-X come in 32 & 64 bit, but the Linux version does not.

**Comment by c-smile** [comment]
By default I am building **only  Windows 32-bit version**  to support Windows XP machines that are pretty much all 32-bit. 

For MacOS and Linux SDK contains only 64-bit versions.

macOS will stop support 32-bit apps next year anyway so it makes no sense to do 32-bit development on that platform. 

Not sure about Linux but mainstream distributions seems like all 64-bit by default.

And yes, you need access to Sciter sources in order to build it for different bitness or processor architecture.

**Comment by GeraldWodni** [comment]
@pravic @c-smile thank you, will bring that up in our next meeting.
