### ISSUE TITLE
Accessing Keyboard Shortcuts

### ISSUE THREAD

**Issue by Syenta** [c-smile/sciter-sdk#97]
Hi,

I have just discovered HTML-Notepad and find it fresh, uncluttered and interesting.

As someone new to your program I would like to be able to access the keyboard shortcuts quickly. Pressing F1, which is the normal way to access help, doesn't work although you may not consider this a help file.

Scanning your shortcut list doesn't provide any help as it is not included within your list. So, might I suggest either implementing F1 to open the shortcuts list or IMHO a better option would be a left pane which pops out and can be pinned open.

Hope this helps

Syenta

**Comment by c-smile** [comment]
Hi Syenta
Well, keyboard shortcuts are meant to be used without any additional help, otherwise you can use just toolbar buttons.

If you do need help to be present on screen at the time of typing then you can open second instance of HTML-NOTEPAD with that list of shortcuts. Will this work for you?

Andrew Fedoniouk

Terra Informatica Software, Inc.

Richmond, BC, Canada

phone:+1(604)244-1074
mailto:andrew@sciter.com
http://sciter.com

From: Syenta
Sent: November 8, 2018 1:26 AM
To: c-smile/sciter-sdk
Cc: Subscribed
Subject: [c-smile/sciter-sdk] Accessing Keyboard Shortcuts (#97)

Hi,
I have just discovered HTML-Notepad and find it fresh, uncluttered and interesting.
As someone new to your program I would like to be able to access the keyboard shortcuts quickly. Pressing F1, which is the normal way to access help, doesn't work although you may not consider this a help file.
Scanning your shortcut list doesn't provide any help as it is not included within your list. So, might I suggest either implementing F1 to open the shortcuts list or IMHO a better option would be a left pane which pops out and can be pinned open.
Hope this helps
Syenta

**Comment by Syenta** [comment]
It's an unusual way to get the keyboard shortcuts but it is a lot quicker than coding this sort of thing. Thanks anyway for getting back to me and for a nice little program.
